require:
  - rubocop-rails

AllCops:
  NewCops: enable

  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
