version: '3.8'

services:
  hello-rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mounts the project folder to '/workspaces'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ../..:/workspaces
      - zsh-volume:/zsh-volume
    environment:
      - LANG=ja_JP.UTF-8
      - REDIS_URL=redis://hello-rails-redis:6379/0
    networks:
      - db-network
      - redis-network

  hello-rails-db:
    # mysql/mysql-server:5.7
    #   - pros
    #     - M1 arm64v8をサポートしている
    #   - cons
    #     - 公式に「The MySQL Docker images maintained by the MySQL team are built specifically for Linux platforms.」と書かれている
    # (M1 Macでも動くので)mysql:5.7でplatform:linux/amd64指定して利用しながら様子見
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: hello_rails_database
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    ports:
      - '3306:3306'
    networks:
      - db-network

  hello-rails-redis:
    image: redis:7.2.4
    ports:
      - '6379:6379'
    networks:
      - redis-network

volumes:
  zsh-volume:
    name: zsh-volume

networks:
  db-network:
    driver: bridge
  redis-network:
    driver: bridge
